function k(b,a,c,d){b.v.yb(b.ab,a,c,d,void 0)}function l(b,a,c,d){b.v.ga?k(b,a,c,d):b.v.oe()._OnMessageFromDOM({type:"event",component:b.ab,handler:a,dispatchOpts:d||null,data:c,responseId:null})}function n(b,a,c){b.v.C(b.ab,a,c)}function aa(b,a){for(const [c,d]of a)n(b,c,d)}function r(b){b.Jb||(b.v.he(b.Gd),b.Jb=!0)}window.wb=class{constructor(b,a){this.v=b;this.ab=a;this.Jb=!1;this.Gd=()=>this.Fa()}Sc(){}Fa(){}};function ba(b){-1!==b.Sa&&(self.clearTimeout(b.Sa),b.Sa=-1)}
window.ee=class{constructor(b){this.zc=b;this.De=5;this.Sa=-1;this.Lb=-Infinity;this.Hd=()=>{this.Sa=-1;this.Lb=Date.now();this.gb=!0;this.zc();this.gb=!1};this.kd=this.gb=!1}j(){ba(this);this.Hd=this.zc=null}};"use strict";function ca(b,a){n(b,"get-element",c=>{const d=b.ea.get(c.elementId);return a(d,c)})}
window.Xe=class extends self.wb{constructor(b,a){super(b,a);this.ea=new Map;this.yc=!0;aa(this,[["create",()=>{throw Error("required override");}],["destroy",c=>{c=c.elementId;const d=this.ea.get(c);this.yc&&d.parentElement.removeChild(d);this.ea.delete(c)}],["set-visible",c=>{this.yc&&(this.ea.get(c.elementId).style.display=c.isVisible?"":"none")}],["update-position",c=>{if(this.yc){var d=this.ea.get(c.elementId);d.style.left=c.left+"px";d.style.top=c.top+"px";d.style.width=c.width+"px";d.style.height=
c.height+"px";c=c.fontSize;null!==c&&(d.style.fontSize=c+"em")}}],["update-state",c=>{this.ea.get(c.elementId);throw Error("required override");}],["focus",c=>{const d=this.ea.get(c.elementId);c.focus?d.focus():d.blur()}],["set-css-style",c=>{this.ea.get(c.elementId).style[c.prop]=c.val}],["set-attribute",c=>{this.ea.get(c.elementId).setAttribute(c.name,c.val)}],["remove-attribute",c=>{this.ea.get(c.elementId).removeAttribute(c.name)}]]);ca(this,c=>c)}};"use strict";
const da=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent),u=/android/i.test(navigator.userAgent);let ea=0;function v(b){const a=document.createElement("script");a.async=!1;a.type="module";return b.Ne?new Promise(c=>{const d="c3_resolve_"+ea;++ea;self[d]=c;a.textContent=b.Re+`\n\nself["${d}"]();`;document.head.appendChild(a)}):new Promise((c,d)=>{a.onload=c;a.onerror=d;a.src=b;document.head.appendChild(a)})}let fa=!1,ha=!1;
function ia(){if(!fa){try{new Worker("blob://",{get type(){ha=!0}})}catch(b){}fa=!0}return ha}let w=new Audio;const ja={"audio/webm; codecs=opus":!!w.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!w.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!w.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!w.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!w.canPlayType("audio/mp4"),"audio/mpeg":!!w.canPlayType("audio/mpeg")};w=null;
async function ka(b){b=await la(b);return(new TextDecoder("utf-8")).decode(b)}function la(b){return new Promise((a,c)=>{const d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsArrayBuffer(b)})}const x=[];let z=0;window.RealFile=window.File;const A=[],B=new Map,D=new Map;let ma=0;const na=[];self.runOnStartup=function(b){if("function"!==typeof b)throw Error("runOnStartup called without a function");na.push(b)};const oa=new Set(["cordova","playable-ad","instant-games"]);
let pa=!1;
window.Ab=class b{constructor(a){this.ga=a.Te;this.sa=null;this.$="";this.$b=a.Qe;this.ub={};this.La=this.tb=null;this.Hb=[];this.H=this.Qa=null;this.Hc=!1;this.nd=0;this.ib=null;this.Pa=-1;this.Ie=()=>this.ve();this.Oa=[];this.D=a.Id;this.Kb="file"===location.protocol.substr(0,4);!this.ga||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&ia()||(this.ga=!1);if("playable-ad"===this.D||"instant-games"===this.D)this.ga=!1;if("cordova"===this.D&&this.ga)if(u){const c=/Chrome\/(\d+)/i.exec(navigator.userAgent);c&&
90<=parseInt(c[1],10)||(this.ga=!1)}else this.ga=!1;this.Ob=this.la=null;"html5"!==this.D||window.isSecureContext||console.warn("[Construct] Warning: the browser indicates this is not a secure context. Some features may be unavailable. Use secure (HTTPS) hosting to ensure all features are available.");this.C("runtime","cordova-fetch-local-file",c=>this.re(c));this.C("runtime","create-job-worker",()=>this.se());"cordova"===this.D?document.addEventListener("deviceready",()=>this.bd(a)):this.bd(a)}j(){this.pc();
this.sa&&(this.sa=this.sa.onmessage=null);this.tb&&(this.tb.terminate(),this.tb=null);this.La&&(this.La.j(),this.La=null);this.H&&(this.H.parentElement.removeChild(this.H),this.H=null)}be(){return da&&"cordova"===this.D}lc(){const a=navigator.userAgent;return da&&oa.has(this.D)||navigator.standalone||/crios\/|fxios\/|edgios\//i.test(a)}$d(){return u}Xc(){return u&&oa.has(this.D)}async bd(a){"macos-wkwebview"===this.D&&this.Ae();if("playable-ad"===this.D){this.la=self.c3_base64files;this.Ob={};await this.ke();
for(let d=0,e=a.Ta.length;d<e;++d){var c=a.Ta[d].toLowerCase();this.Ob.hasOwnProperty(c)?a.Ta[d]={Ne:!0,Re:this.Ob[c]}:this.la.hasOwnProperty(c)&&(a.Ta[d]=URL.createObjectURL(this.la[c]))}}a.Pe?this.$=a.Pe:(c=location.origin,this.$=("null"===c?"file:///":c)+location.pathname,c=this.$.lastIndexOf("/"),-1!==c&&(this.$=this.$.substr(0,c+1)));a.Ve&&(this.ub=a.Ve);c=new MessageChannel;this.sa=c.port1;this.sa.onmessage=d=>this._OnMessageFromRuntime(d.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(d=>
this.ue(d));this.ib=new self.ce(this);await qa(this.ib);"object"===typeof window.StatusBar&&window.StatusBar.hide();if("object"===typeof window.AndroidFullScreen)try{await new Promise((d,e)=>{window.AndroidFullScreen.immersiveMode(d,e)})}catch(d){console.error("Failed to enter Android immersive mode: ",d)}this.ga?await this.qe(a,c.port2):await this.pe(a,c.port2)}rc(a){a=this.ub.hasOwnProperty(a)?this.ub[a]:a.endsWith("/workermain.js")&&this.ub.hasOwnProperty("workermain.js")?this.ub["workermain.js"]:
"playable-ad"===this.D&&this.la.hasOwnProperty(a.toLowerCase())?this.la[a.toLowerCase()]:a;a instanceof Blob&&(a=URL.createObjectURL(a));return a}async fc(a,c,d){if(a.startsWith("blob:"))return new Worker(a,d);if("cordova"===this.D&&this.Kb)return a=await this.vb(d.Me?a:this.$b+a),new Worker(URL.createObjectURL(new Blob([a],{type:"application/javascript"})),d);a=new URL(a,c);if(location.origin!==a.origin){a=await fetch(a);if(!a.ok)throw Error("failed to fetch worker script");a=await a.blob();return new Worker(URL.createObjectURL(a),
d)}return new Worker(a,d)}qa(){return Math.max(window.innerWidth,1)}ia(){return Math.max(window.innerHeight,1)}ad(a){var c=this.$,d=location.href,e=this.qa(),f=this.ia(),g=window.devicePixelRatio,h=b.Xa(),m=a.af,p=window.cr_previewImageBlobs||this.la,q=window.cr_previewProjectFileBlobs,t=window.cr_previewProjectFiles,y=window.Ze||"";a=a.Id;var V=(new URLSearchParams(self.location.search)).has("debug"),C=this.ib;return{runtimeBaseUrl:c,previewUrl:d,windowInnerWidth:e,windowInnerHeight:f,devicePixelRatio:g,
isFullscreen:h,projectData:m,previewImageBlobs:p,previewProjectFileBlobs:q,previewProjectFileSWUrls:t,swClientId:y,exportType:a,isDebug:V,ife:!!self.$e,jobScheduler:{inputPort:C.Gc,outputPort:C.Mc,maxNumWorkers:C.Fe},supportedAudioFormats:ja,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.$b+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.$b+"opus.wasm.wasm",isFileProtocol:this.Kb,isiOSCordova:this.be(),isiOSWebView:this.lc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async qe(a,
c){var d=this.rc(a.Ue);this.tb=await this.fc(d,this.$,{type:"module",name:"Runtime",Me:!0});this.H=document.createElement("canvas");this.H.style.display="none";d=this.H.transferControlToOffscreen();document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();let e=a.Rc||[],f=a.Ta;e=await Promise.all(e.map(g=>this.Ga(g)));f=await Promise.all(f.map(g=>this.Ga(g)));if("cordova"===this.D)for(let g=0,h=a.cc.length;g<h;++g){const m=a.cc[g],p=
m[0];if(p===a.Pc||"scriptsInEvents.js"===p||p.endsWith("/scriptsInEvents.js"))m[1]=await this.Ga(p)}this.tb.postMessage(Object.assign(this.ad(a),{type:"init-runtime",isInWorker:!0,messagePort:c,canvas:d,workerDependencyScripts:e,engineScripts:f,projectScripts:a.cc,mainProjectScript:a.Pc,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[c,d,...ra(this.ib)]);this.Hb=A.map(g=>new g(this));this.$c();self.c3_callFunction=(g,h)=>{var m=this.Qa;return m.v.Zc(m.ab,"js-invoke-function",{name:g,params:h},
void 0,void 0)};"preview"===this.D&&(self.goToLastErrorScript=()=>this.yb("runtime","go-to-last-error-script"))}async pe(a,c){this.H=document.createElement("canvas");this.H.style.display="none";document.body.appendChild(this.H);window.c3canvas=this.H;self.C3_InsertHTMLPlaceholders&&self.C3_InsertHTMLPlaceholders();this.Hb=A.map(g=>new g(this));this.$c();var d=a.Ta.map(g=>"string"===typeof g?(new URL(g,this.$)).toString():g);Array.isArray(a.Rc)&&d.unshift(...a.Rc);d=await Promise.all(d.map(g=>this.Ga(g)));
await Promise.all(d.map(g=>v(g)));d=self.C3_ProjectScriptsStatus;const e=a.Pc,f=a.cc;for(let [g,h]of f)if(h||=g,g===e)try{h=await this.Ga(h),await v(h),"preview"!==this.D||d[g]||this.dd(g,"main script did not run to completion")}catch(m){this.dd(g,m)}else if("scriptsInEvents.js"===g||g.endsWith("/scriptsInEvents.js"))h=await this.Ga(h),await v(h);"preview"===this.D&&"object"!==typeof self.We.Ye?(this.Db(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(a=Object.assign(this.ad(a),{isInWorker:!1,messagePort:c,canvas:this.H,runOnStartupFunctions:na}),this.cd(),this.La=self.C3_CreateRuntime(a),await self.C3_InitRuntime(this.La,a))}dd(a,c){this.Db();console.error(`[Preview] Failed to load project main script (${a}): `,c);alert(`Failed to load project main script (${a}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}cd(){this.Db()}Db(){const a=
window.Ke;a&&(a.parentElement.removeChild(a),window.Ke=null)}async se(){const a=await sa(this.ib);return{outputPort:a,transferables:[a]}}oe(){if(this.ga)throw Error("not available in worker mode");return this.La}yb(a,c,d,e,f){this.sa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:null},f)}Zc(a,c,d,e,f){const g=ma++,h=new Promise((m,p)=>{D.set(g,{resolve:m,reject:p})});this.sa.postMessage({type:"event",component:a,handler:c,dispatchOpts:e||null,data:d,responseId:g},
f);return h}_OnMessageFromRuntime(a){const c=a.type;if("event"===c)return this.te(a);if("result"===c)this.we(a);else if("runtime-ready"===c)this.xe();else if("alert-error"===c)this.Db(),alert(a.message);else if("creating-runtime"===c)this.cd();else throw Error(`unknown message '${c}'`);}te(a){const c=a.component,d=a.handler,e=a.data,f=a.responseId;if(a=B.get(c))if(a=a.get(d)){var g=null;try{g=a(e)}catch(h){console.error(`Exception in '${c}' handler '${d}':`,h);null!==f&&this.Cb(f,!1,""+h);return}if(null===
f)return g;g&&g.then?g.then(h=>this.Cb(f,!0,h)).catch(h=>{console.error(`Rejection from '${c}' handler '${d}':`,h);this.Cb(f,!1,""+h)}):this.Cb(f,!0,g)}else console.warn(`[DOM] No handler '${d}' for component '${c}'`);else console.warn(`[DOM] No event handlers for component '${c}'`)}Cb(a,c,d){let e;d&&d.transferables&&(e=d.transferables);this.sa.postMessage({type:"result",responseId:a,isOk:c,result:d},e)}we(a){const c=a.responseId,d=a.isOk;a=a.result;const e=D.get(c);d?e.resolve(a):e.reject(a);D.delete(c)}C(a,
c,d){let e=B.get(a);e||(e=new Map,B.set(a,e));if(e.has(c))throw Error(`[DOM] Component '${a}' already has handler '${c}'`);e.set(c,d)}static dc(a){if(A.includes(a))throw Error("DOM handler already added");A.push(a)}$c(){for(const a of this.Hb)if("runtime"===a.ab){this.Qa=a;return}throw Error("cannot find runtime DOM handler");}ue(a){this.yb("debugger","message",a)}xe(){for(const a of this.Hb)a.Sc()}static Xa(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
pa)}static ed(a){pa=!!a}he(a){this.Oa.push(a);this.wc()}ze(a){a=this.Oa.indexOf(a);if(-1===a)throw Error("invalid callback");this.Oa.splice(a,1);this.Oa.length||this.pc()}wc(){-1===this.Pa&&this.Oa.length&&(this.Pa=requestAnimationFrame(this.Ie))}pc(){-1!==this.Pa&&(cancelAnimationFrame(this.Pa),this.Pa=-1)}ve(){this.Pa=-1;for(const a of this.Oa)a();this.wc()}wa(a){this.Qa.wa(a)}Ea(a){this.Qa.Ea(a)}vc(){this.Qa.vc()}Bb(a){this.Qa.Bb(a)}ae(){return!!ja["audio/webm; codecs=opus"]}async Be(a){a=await this.Zc("runtime",
"opus-decode",{arrayBuffer:a},null,[a]);return new Float32Array(a)}fe(a){this.Hc=!0;this.nd=a}Zd(a){return/^(?:[a-z\-]+:)?\/\//.test(a)||"data:"===a.substr(0,5)||"blob:"===a.substr(0,5)}Yc(a){return!this.Zd(a)}async Ga(a){return"cordova"===this.D&&(a.startsWith("file:")||this.Kb&&this.Yc(a))?(a.startsWith(this.$)&&(a=a.substr(this.$.length)),a=await this.vb(a),URL.createObjectURL(new Blob([a],{type:"application/javascript"}))):a}async re(a){const c=a.filename;switch(a.as){case "text":return await this.Yd(c);
case "buffer":return await this.vb(c);default:throw Error("unsupported type");}}Vc(a){const c=window.cordova.file.applicationDirectory+"www/"+a.toLowerCase();return new Promise((d,e)=>{window.resolveLocalFileSystemURL(c,f=>{f.file(d,e)},e)})}async Yd(a){a=await this.Vc(a);return await ka(a)}qc(){if(x.length&&!(8<=z)){z++;var a=x.shift();this.le(a.filename,a.Se,a.Le)}}vb(a){return new Promise((c,d)=>{x.push({filename:a,Se:e=>{z--;this.qc();c(e)},Le:e=>{z--;this.qc();d(e)}});this.qc()})}async le(a,
c,d){try{const e=await this.Vc(a),f=await la(e);c(f)}catch(e){d(e)}}Ae(){var a={type:"ready"};if("windows-webview2"===this.D)window.chrome.webview.postMessage(JSON.stringify(a));else if("macos-wkwebview"===this.D)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(a));else throw Error("cannot send wrapper message");}async ke(){const a=[];for(const [c,d]of Object.entries(this.la))a.push(this.je(c,d));await Promise.all(a)}async je(a,c){if("object"===typeof c)this.la[a]=new Blob([c.str],
{type:c.type}),this.Ob[a]=c.str;else{let d=await this.ne(c);d||=this.me(c);this.la[a]=d}}async ne(a){try{return await (await fetch(a)).blob()}catch(c){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",c),null}}me(a){a=this.ye(a);return this.ie(a.data,a.Oe)}ye(a){var c=a.indexOf(",");if(0>c)throw new URIError("expected comma in data: uri");
var d=a.substring(c+1);c=a.substring(5,c).split(";");a=c[0]||"";const e=c[2];d="base64"===c[1]||"base64"===e?atob(d):decodeURIComponent(d);return{Oe:a,data:d}}ie(a,c){var d=a.length;let e=d>>2,f=new Uint8Array(d),g=new Uint32Array(f.buffer,0,e),h,m;for(m=h=0;h<e;++h)g[h]=a.charCodeAt(m++)|a.charCodeAt(m++)<<8|a.charCodeAt(m++)<<16|a.charCodeAt(m++)<<24;for(d&=3;d--;)f[m]=a.charCodeAt(m),++m;return new Blob([f],{type:c})}};"use strict";const E=self.Ab;
function ta(b){return b.sourceCapabilities&&b.sourceCapabilities.firesTouchEvents||b.originalEvent&&b.originalEvent.sourceCapabilities&&b.originalEvent.sourceCapabilities.firesTouchEvents}const ua=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),F={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},va={dispatchUserScriptEvent:!0},G={dispatchRuntimeEvent:!0};
function wa(b){return new Promise((a,c)=>{const d=document.createElement("link");d.onload=()=>a(d);d.onerror=e=>c(e);d.rel="stylesheet";d.href=b;document.head.appendChild(d)})}function xa(b){return new Promise((a,c)=>{const d=new Image;d.onload=()=>a(d);d.onerror=e=>c(e);d.src=b})}async function H(b){b=URL.createObjectURL(b);try{return await xa(b)}finally{URL.revokeObjectURL(b)}}
function ya(b){return new Promise((a,c)=>{let d=new FileReader;d.onload=e=>a(e.target.result);d.onerror=e=>c(e);d.readAsText(b)})}
async function za(b,a,c){if(!/firefox/i.test(navigator.userAgent))return await H(b);var d=await ya(b);d=(new DOMParser).parseFromString(d,"image/svg+xml");const e=d.documentElement;if(e.hasAttribute("width")&&e.hasAttribute("height")){const f=e.getAttribute("width"),g=e.getAttribute("height");if(!f.includes("%")&&!g.includes("%"))return await H(b)}e.setAttribute("width",a+"px");e.setAttribute("height",c+"px");d=(new XMLSerializer).serializeToString(d);b=new Blob([d],{type:"image/svg+xml"});return await H(b)}
function I(b){do{if(b.parentNode&&b.hasAttribute("contenteditable"))return!0;b=b.parentNode}while(b);return!1}const Aa=new Set(["input","textarea","datalist","select"]),Ba=new Set(["canvas","body","html"]);function J(b){Ba.has(b.target.tagName.toLowerCase())&&b.preventDefault()}function Ca(b){(b.metaKey||b.ctrlKey)&&b.preventDefault()}
self.C3_GetSvgImageSize=async function(b){b=await H(b);if(0<b.width&&0<b.height)return[b.width,b.height];b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.visibility="hidden";document.body.appendChild(b);const a=b.getBoundingClientRect();document.body.removeChild(b);return[a.width,a.height]};self.C3_RasterSvgImageBlob=async function(b,a,c,d,e){b=await za(b,a,c);const f=document.createElement("canvas");f.width=d;f.height=e;f.getContext("2d").drawImage(b,0,0,a,c);return f};
let K=!1;document.addEventListener("pause",()=>K=!0);document.addEventListener("resume",()=>K=!1);async function Da(b){var a=b.imageBitmapOpts;b=await self.C3_RasterSvgImageBlob(b.blob,b.imageWidth,b.imageHeight,b.surfaceWidth,b.surfaceHeight);a=a?await createImageBitmap(b,a):await createImageBitmap(b);return{imageBitmap:a,transferables:[a]}}async function Fa(b){return await self.C3_GetSvgImageSize(b.blob)}
function Ga(b){window.c3_postToMessagePort&&(b.from="runtime",window.c3_postToMessagePort(b))}function Ha(b){self.setTimeout(()=>{b.md=!0},1E3);"cordova"===b.v.D?(document.addEventListener("pause",()=>L(b,!0)),document.addEventListener("resume",()=>L(b,!1))):document.addEventListener("visibilitychange",()=>L(b,document.hidden));return{isSuspended:!(!document.hidden&&!K)}}
function Ia(b){b.gd||(b.gd=!0,window.addEventListener("deviceorientation",a=>{b.Y||k(b,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},F)}),window.addEventListener("deviceorientationabsolute",a=>{b.Y||k(b,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},F)}))}
function Ja(b){b.fd||(b.fd=!0,window.addEventListener("devicemotion",a=>{if(!b.Y){var c=null,d=a.acceleration;d&&(c={x:d.x||0,y:d.y||0,z:d.z||0});d=null;var e=a.accelerationIncludingGravity;e&&(d={x:e.x||0,y:e.y||0,z:e.z||0});e=null;var f=a.rotationRate;f&&(e={alpha:f.alpha||0,beta:f.beta||0,gamma:f.gamma||0});k(b,"devicemotion",{acceleration:c,accelerationIncludingGravity:d,rotationRate:e,interval:a.interval,timeStamp:a.timeStamp},F)}}))}async function Ka(b){await wa(b.url)}
function La(b,a){b.od=a.message;-1===b.Cc&&(b.Cc=setTimeout(()=>{b.Cc=-1;const c=document.getElementById("exportToVideoMessage");c&&(c.textContent=b.od)},250))}function M(b){if(!b.Y){var a=E.Xa();a&&"any"!==b.Nc&&Ma(b);k(b,"fullscreenchange",{isFullscreen:a,innerWidth:b.qa(),innerHeight:b.ia()})}}function Na(b,a){console.warn("[Construct] Fullscreen request failed: ",a);k(b,"fullscreenerror",{isFullscreen:E.Xa(),innerWidth:b.qa(),innerHeight:b.ia()})}
function L(b,a){a?b.v.pc():b.v.wc();k(b,"visibilitychange",{hidden:a})}function Oa(b,a,c){"Backspace"===c.key&&J(c);if(!b.Y){var d=ua.get(c.code)||c.code;l(b,a,{code:d,key:c.key,which:c.which,repeat:c.repeat,altKey:c.altKey,ctrlKey:c.ctrlKey,metaKey:c.metaKey,shiftKey:c.shiftKey,timeStamp:c.timeStamp},F)}}
function Pa(b,a,c,d){b.Y||ta(c)||l(b,a,{button:c.button,buttons:c.buttons,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:c.movementX||0,movementY:c.movementY||0,timeStamp:c.timeStamp},d)}function Qa(b){window!==window.top&&window.focus();Ra(b.target)&&document.activeElement&&!Ra(document.activeElement)&&document.activeElement.blur()}
function N(b,a,c){if(!b.Y){if(b.qb&&"pointermove"!==a){var d=b.qb;d.gb||(ba(d),d.Lb=Date.now())}d=0;"mouse"===c.pointerType&&(d=b.nb);l(b,a,{pointerId:c.pointerId,pointerType:c.pointerType,button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:(c.movementX||0)+b.Vb,movementY:(c.movementY||0)+b.Wb,width:c.width||0,height:c.height||0,pressure:c.pressure||0,tangentialPressure:c.tangentialPressure||0,tiltX:c.tiltX||0,tiltY:c.tiltY||0,
twist:c.twist||0,timeStamp:c.timeStamp},F);b.Vb=0;b.Wb=0;"mouse"===c.pointerType&&(d="mousemove","pointerdown"===a?d="mousedown":"pointerup"===a&&(d="mouseup"),Pa(b,d,c,va),b.nb=c.buttons)}}
function Sa(b,a,c){if(!b.Y&&!ta(c)){var d=b.nb;"pointerdown"===a&&0!==d?a="pointermove":"pointerup"===a&&0!==c.buttons&&(a="pointermove");l(b,a,{pointerId:1,pointerType:"mouse",button:c.button,buttons:c.buttons,lastButtons:d,clientX:c.clientX,clientY:c.clientY,pageX:c.pageX,pageY:c.pageY,movementX:c.movementX||0,movementY:c.movementY||0,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:c.timeStamp},F);b.nb=c.buttons;Pa(b,c.type,c,va)}}
function O(b,a,c){if(!b.Y)for(let d=0,e=c.changedTouches.length;d<e;++d){const f=c.changedTouches[d];l(b,a,{pointerId:f.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:f.clientX,clientY:f.clientY,pageX:f.pageX,pageY:f.pageY,movementX:c.movementX||0,movementY:c.movementY||0,width:2*(f.radiusX||f.webkitRadiusX||0),height:2*(f.radiusY||f.webkitRadiusY||0),pressure:f.force||f.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:f.rotationAngle||0,timeStamp:c.timeStamp},F)}}
function Ta(b,a){document.body.style.transform="";if(0<a){var c=document.activeElement;c&&(c=c.getBoundingClientRect(),b=(c.top+c.bottom)/2-(b-a)/2,b>a&&(b=a),0>b&&(b=0),0<b&&(document.body.style.transform=`translateY(${-b}px)`))}}function Va(b,a,c,d){const e=b.qa(),f=b.ia();b.Ra=-1;e!=a||f!=c?k(b,"window-resize",{innerWidth:e,innerHeight:f,devicePixelRatio:window.devicePixelRatio,isFullscreen:E.Xa()}):10>d&&Wa(b,e,f,d+1)}
function Wa(b,a,c,d){-1!==b.Ra&&clearTimeout(b.Ra);b.Ra=setTimeout(()=>Va(b,a,c,d),48)}
function Ma(b){b=b.Nc;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(b).catch(a=>console.warn("[Construct] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(b):screen.webkitLockOrientation?a=screen.webkitLockOrientation(b):screen.mozLockOrientation?a=screen.mozLockOrientation(b):screen.msLockOrientation&&(a=screen.msLockOrientation(b));a||console.warn("[Construct] Failed to lock orientation")}catch(a){console.warn("[Construct] Failed to lock orientation: ",
a)}}function Ra(b){return!b||b===document||b===window||b===document.body||"canvas"===b.tagName.toLowerCase()}
E.dc(class extends self.wb{constructor(b){super(b,"runtime");this.td=!0;this.Ra=-1;this.Nc="any";this.fd=this.gd=!1;this.za=null;this.Y=!1;this.od="";this.Cc=-1;this.Ka=this.qb=null;this.Wb=this.Vb=0;this.md=!1;this.xd=b.qa();this.Mb=b.ia();this.sb=0;b.C("canvas","update-size",d=>{var e=this.v;e.Hc||(e=e.H,e.style.width=d.styleWidth+"px",e.style.height=d.styleHeight+"px",e.style.marginLeft=d.marginLeft+"px",e.style.marginTop=d.marginTop+"px",this.td&&(e.style.display="",this.td=!1))});b.C("runtime",
"invoke-download",d=>{const e=d.url;d=d.filename;const f=document.createElement("a"),g=document.body;f.textContent=d;f.href=e;f.download=d;g.appendChild(f);f.click();g.removeChild(f)});b.C("runtime","raster-svg-image",d=>Da(d));b.C("runtime","get-svg-image-size",d=>Fa(d));b.C("runtime","set-target-orientation",d=>{this.Nc=d.targetOrientation});b.C("runtime","register-sw",()=>{window.C3_RegisterSW&&window.C3_RegisterSW()});b.C("runtime","post-to-debugger",d=>Ga(d));b.C("runtime","go-to-script",d=>
Ga(d));b.C("runtime","before-start-ticking",()=>Ha(this));b.C("runtime","debug-highlight",d=>{if(d.show){this.za||(this.za=document.createElement("div"),this.za.id="inspectOutline",document.body.appendChild(this.za));var e=this.za;e.style.display="";e.style.left=d.left-1+"px";e.style.top=d.top-1+"px";e.style.width=d.width+2+"px";e.style.height=d.height+2+"px";e.textContent=d.name}else this.za&&(this.za.style.display="none")});b.C("runtime","enable-device-orientation",()=>Ia(this));b.C("runtime","enable-device-motion",
()=>Ja(this));b.C("runtime","add-stylesheet",d=>Ka(d));b.C("runtime","alert",d=>{alert(d.message)});b.C("runtime","hide-cordova-splash",()=>{navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()});b.C("runtime","set-exporting-to-video",d=>{this.Y=!0;const e=document.createElement("h1");e.id="exportToVideoMessage";e.textContent=d.message;document.body.prepend(e);document.body.classList.add("exportingToVideo");this.v.H.style.display="";this.v.fe(d.duration)});b.C("runtime",
"export-to-video-progress",d=>La(this,d));b.C("runtime","exported-to-video",d=>{window.Je({type:"exported-video",blob:d.blob,time:d.time})});b.C("runtime","exported-to-image-sequence",d=>{window.Je({type:"exported-image-sequence",blobArr:d.blobArr,time:d.time})});const a=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",d=>{const e=d.target;a.has(e.tagName.toLowerCase())||I(e)||d.preventDefault()});const c=b.H;window.addEventListener("selectstart",J);window.addEventListener("gesturehold",
J);c.addEventListener("selectstart",J);c.addEventListener("gesturehold",J);window.addEventListener("touchstart",J,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",J,{passive:!1}),c.addEventListener("pointerdown",J)):c.addEventListener("touchstart",J);this.nb=0;window.addEventListener("mousedown",d=>{1===d.button&&d.preventDefault()});window.addEventListener("mousewheel",Ca,{passive:!1});window.addEventListener("wheel",Ca,{passive:!1});window.addEventListener("resize",
()=>{a:{if(!this.Y){var d=this.qa();var e=this.ia();if(this.v.Xc()){if(this.md){if(this.xd===d&&e<this.Mb){this.sb=this.Mb-e;Ta(this.Mb,this.sb);d=void 0;break a}0<this.sb&&(this.sb=0,Ta(e,this.sb))}this.xd=d;this.Mb=e}k(this,"window-resize",{innerWidth:d,innerHeight:e,devicePixelRatio:window.devicePixelRatio,isFullscreen:E.Xa()});this.v.lc()&&(-1!==this.Ra&&clearTimeout(this.Ra),Va(this,d,e,0))}d=void 0}return d});window.addEventListener("fullscreenchange",()=>M(this));window.addEventListener("webkitfullscreenchange",
()=>M(this));window.addEventListener("mozfullscreenchange",()=>M(this));window.addEventListener("fullscreenerror",d=>Na(this,d));window.addEventListener("webkitfullscreenerror",d=>Na(this,d));window.addEventListener("mozfullscreenerror",d=>Na(this,d));if(b.lc())if(window.visualViewport){let d=Infinity;window.visualViewport.addEventListener("resize",()=>{const e=window.visualViewport.height;e>d&&(document.scrollingElement.scrollTop=0);d=e})}else window.addEventListener("focusout",()=>{{const f=document.activeElement;
if(f){var d=f.tagName.toLowerCase();var e=new Set("email number password search tel text url".split(" "));d="textarea"===d?!0:"input"===d?e.has(f.type.toLowerCase()||"text"):I(f)}else d=!1}d||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=d=>{"entered-fullscreen"===d?(E.ed(!0),M(this)):"exited-fullscreen"===d?(E.ed(!1),M(this)):console.warn("Unknown wrapper message: ",d)};this.Ma=new Set;this.Qb=new WeakSet;this.ra=!1}Sc(){window.addEventListener("focus",()=>{k(this,"window-focus",
null,G)});window.addEventListener("blur",()=>{try{var a=window.parent&&window.parent.document.hasFocus()}catch(c){a=!1}k(this,"window-blur",{parentHasFocus:a},G);this.nb=0});window.addEventListener("focusin",a=>{a=a.target;(Aa.has(a.tagName.toLowerCase())||I(a))&&k(this,"keyboard-blur",null,G)});window.addEventListener("keydown",a=>Oa(this,"keydown",a));window.addEventListener("keyup",a=>Oa(this,"keyup",a));window.addEventListener("dblclick",a=>Pa(this,"dblclick",a,F));window.addEventListener("wheel",
a=>{this.Y||k(this,"wheel",{clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},F)});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",a=>{Qa(a);N(this,"pointerdown",a)}),this.v.ga&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.qb=new self.ee(()=>{N(this,"pointermove",this.Ka);this.Ka=null}),this.qb.kd=!0,window.addEventListener("pointerrawupdate",
a=>{this.Ka&&(this.Vb+=this.Ka.movementX||0,this.Wb+=this.Ka.movementY||0);this.Ka=a;a=this.qb;if(-1===a.Sa){var c=Date.now(),d=c-a.Lb,e=a.De;d>=e&&a.kd?(a.Lb=c,a.gb=!0,a.zc(),a.gb=!1):a.Sa=self.setTimeout(a.Hd,Math.max(e-d,4))}})):window.addEventListener("pointermove",a=>N(this,"pointermove",a)),window.addEventListener("pointerup",a=>N(this,"pointerup",a)),window.addEventListener("pointercancel",a=>N(this,"pointercancel",a))):(window.addEventListener("mousedown",a=>{Qa(a);Sa(this,"pointerdown",a)}),
window.addEventListener("mousemove",a=>Sa(this,"pointermove",a)),window.addEventListener("mouseup",a=>Sa(this,"pointerup",a)),window.addEventListener("touchstart",a=>{Qa(a);O(this,"pointerdown",a)}),window.addEventListener("touchmove",a=>O(this,"pointermove",a)),window.addEventListener("touchend",a=>O(this,"pointerup",a)),window.addEventListener("touchcancel",a=>O(this,"pointercancel",a)));const b=()=>this.vc();window.addEventListener("pointerup",b,!0);window.addEventListener("touchend",b,!0);window.addEventListener("click",
b,!0);window.addEventListener("keydown",b,!0);window.addEventListener("gamepadconnected",b,!0);this.v.$d()&&!this.v.Xc()&&navigator.virtualKeyboard&&(navigator.virtualKeyboard.overlaysContent=!0,navigator.virtualKeyboard.addEventListener("geometrychange",()=>{Ta(this.ia(),navigator.virtualKeyboard.boundingRect.height)}))}qa(){return this.v.qa()}ia(){return this.v.ia()}vc(){var b=[...this.Ma];this.Ma.clear();if(!this.ra)for(const a of b)(b=a.play())&&b.catch(()=>{this.Qb.has(a)||this.Ma.add(a)})}wa(b){if("function"!==
typeof b.play)throw Error("missing play function");this.Qb.delete(b);let a;try{a=b.play()}catch(c){this.Ma.add(b);return}a&&a.catch(()=>{this.Qb.has(b)||this.Ma.add(b)})}Ea(b){this.Ma.delete(b);this.Qb.add(b)}Bb(b){this.ra=!!b}});"use strict";
async function qa(b){if(b.Ce)throw Error("already initialised");b.Ce=!0;var a=b.Zb.rc("dispatchworker.js");b.Bc=await b.Zb.fc(a,b.$a,{name:"DispatchWorker"});a=new MessageChannel;b.Gc=a.port1;b.Bc.postMessage({type:"_init","in-port":a.port2},[a.port2]);b.Mc=await sa(b)}function ra(b){return[b.Gc,b.Mc]}
async function sa(b){const a=b.ud.length;var c=b.Zb.rc("jobworker.js");c=await b.Zb.fc(c,b.$a,{name:"JobWorker"+a});const d=new MessageChannel,e=new MessageChannel;b.Bc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);c.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":e.port2},[d.port2,e.port2]);b.ud.push(c);return e.port1}
self.ce=class{constructor(b){this.Zb=b;this.$a=b.$;this.$a="preview"===b.D?this.$a+"workers/":this.$a+b.$b;this.Fe=Math.min(navigator.hardwareConcurrency||2,16);this.Bc=null;this.ud=[];this.Mc=this.Gc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.Ab({Te:!0,Ue:"workermain.js",Ta:["scripts/c3runtime.js"],cc:[],Pc:"",Qe:"scripts/",Rc:[],Id:"html5"}));"use strict";const Xa=180/Math.PI;
async function Ya(b,a){a.isiOSCordova&&(b.Tb=!0);b.Oc=a.timeScaleMode;b.zd=["equalpower","HRTF","soundfield"][a.panningModel];b.ld=["linear","inverse","exponential"][a.distanceModel];b.Ad=a.refDistance;b.yd=a.maxDistance;b.Cd=a.rolloffFactor;if(b.v.Hc)b.Tb=!0,b.g=new OfflineAudioContext({numberOfChannels:2,sampleRate:48E3,length:Math.ceil(48E3*b.v.nd)});else{var c={latencyHint:a.latencyHint};b.Fd||(c.sampleRate=48E3);if("undefined"!==typeof AudioContext)b.g=new AudioContext(c);else if("undefined"!==
typeof webkitAudioContext)b.g=new webkitAudioContext(c);else throw Error("Web Audio API not supported");Za(b);b.g.onstatechange=()=>{"running"!==b.g.state&&Za(b);k(b,"audiocontext-state",{audioContextState:b.g.state})}}b.Ia=b.g.createGain();b.Ia.connect(b.g.destination);c=a.listenerPos;b.g.listener.setPosition(c[0],c[1],c[2]);b.g.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>b.g.currentTime;try{await Promise.all(a.preloadList.map(d=>P(b,d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct] Preloading sounds failed: ",
d)}return{sampleRate:b.g.sampleRate,audioContextState:b.g.state}}
async function $a(b,a){var c=a.originalUrl;const d=a.url,e=a.type,f=a.isMusic,g=a.tag,h=a.isLooping,m=a.vol,p=a.pos,q=a.panning;let t=a.off;0<t&&!a.trueClock&&(b.g.getOutputTimestamp?(a=b.g.getOutputTimestamp(),t=t-a.performanceTime/1E3+a.contextTime):t=t-performance.now()/1E3+b.g.currentTime);b.vd=g;ab(b,g);try{b.ka=await bb(b,c,d,e,g,f);if(q){Q(b.ka,!0);var y=b.ka,V=q.innerAngle,C=q.outerAngle,nb=q.outerGain;if(y.hb){cb(y,q.x,q.y,q.angle);var Ea=self.Ua.ge;y.F.coneInnerAngle=Ea(V);y.F.coneOuterAngle=
Ea(C);y.F.coneOuterGain=nb}q.hasOwnProperty("uid")&&(b.ka.ja=q.uid)}else Q(b.ka,!1);b.ka.Play(h,m,p,t)}catch(ob){console.error("[Construct] Audio: error starting playback: ",ob);return}finally{c=b.pb.get(g);if(!c)throw Error("expected pending tag");c.Qc--;0===c.Qc&&(c.resolve(),b.pb.delete(g))}r(b)}
async function db(b,a){var c=a.tag;const d=a.vol,e=a.duration;a=a.stopOnEnd;await eb(b,c);for(const q of R(b,c)){c=q;var f=d,g=e,h=a;if(!c.Ja){var m=c.N.gain;m.cancelScheduledValues(0);var p=c.s.g.currentTime;g=p+g;m.setValueAtTime(m.value,p);m.linearRampToValueAtTime(f,g);c.Ca=f;c.eb=g;c.Ed=h}}S(b)}async function fb(b,a){const c=a.tag;a=a.rate;await eb(b,c);for(const d of R(b,c))b=d,b.fa!==a&&(b.fa=a,b.xa())}
async function gb(b,a){const c=a.tag;a=a.pos;await eb(b,c);for(const d of R(b,c))d.mc(a)}async function hb(b,a){const c=a.originalUrl,d=a.url,e=a.type;a=a.isMusic;try{await bb(b,c,d,e,"",a)}catch(f){console.error("[Construct] Audio: error preloading: ",f)}}async function ib(b,a){if(a=await P(b,"",a.url,a.type,a.isMusic,!0))a.j(),a=b.ca.indexOf(a),-1!==a&&b.ca.splice(a,1)}
async function jb(b,a){var c=a.type,d=a.tag,e=a.params;if("filter"===c)e=new self.Od(b,...e);else if("delay"===c)e=new self.Md(b,...e);else if("convolution"===c){c=null;try{c=await P(b,a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(g){console.log("[Construct] Audio: error loading convolution: ",g);return}c=e=new self.Ld(b,c.ba,...e);var f=a.bufferType;c.hd=a.bufferOriginalUrl;c.jd=f}else if("flanger"===c)e=new self.Pd(b,...e);else if("phaser"===c)e=new self.Rd(b,...e);else if("gain"===c)e=
new self.Qd(b,...e);else if("tremolo"===c)e=new self.Td(b,...e);else if("ringmod"===c)e=new self.Sd(b,...e);else if("distortion"===c)e=new self.Nd(b,...e);else if("compressor"===c)e=new self.Kd(b,...e);else if("analyser"===c)e=new self.Jd(b,...e);else throw Error("invalid effect type");a=e;d=d.toLowerCase();e=b.da.get(d);e||(e=[],b.da.set(d,e));a.sd=e.length;a.aa=d;e.push(a);kb(b,d);lb(b)}
async function mb(b,a){const c=a.saveLoadMode;if(3!==c)for(var d of b.L)d.va()&&1===c||(d.va()||2!==c)&&d.pa();for(const e of b.da.values())for(const f of e)f.j();b.da.clear();b.ac=a.timeScale;b.Dc=a.gameTime;d=a.listenerPos;b.g.listener.setPosition(d[0],d[1],d[2]);b.ra=a.isSilent;b.v.Bb(b.ra);b.Pb=a.masterVolume;b.Ia.gain.value=b.Pb;d=[];for(const e of Object.values(a.effects))d.push(Promise.all(e.map(f=>jb(b,f))));await Promise.all(d);await Promise.all(a.playing.map(e=>pb(b,e,c)));S(b)}
async function qb(b,a){try{const c=b.g.suspend(a.time);b.rd?b.g.resume():(b.g.startRendering().then(d=>{const e=[];for(let f=0,g=d.numberOfChannels;f<g;++f){const h=d.getChannelData(f);e.push(h.buffer)}b.v.yb("runtime","offline-audio-render-completed",{duration:d.duration,length:d.length,numberOfChannels:d.numberOfChannels,sampleRate:d.sampleRate,channelData:e},null,e)}).catch(d=>rb(d)),b.rd=!0);await c}catch(c){rb(c)}}
function Za(b){b.Ib||(b.Fc=!1,window.addEventListener("pointerup",b.ta,!0),window.addEventListener("touchend",b.ta,!0),window.addEventListener("click",b.ta,!0),window.addEventListener("keydown",b.ta,!0),b.Ib=!0)}
async function P(b,a,c,d,e,f){for(var g of b.ca)if(g.Wa()===c)return await sb(g),g;if(f)return null;if(e&&(b.Tb||b.qd)){f=0;for(let h=0,m=b.ca.length;h<m;++h)g=b.ca[h],b.ca[f]=g,g.va()?g.j():++f;b.ca.length=f}f="audio/webm; codecs=opus"===d&&!b.Fd;e&&f&&(b.qd=!0);a=!e||b.Tb||f?new self.Wd(b,a,c,d,e,f):new self.Ud(b,a,c,d,e);b.ca.push(a);await sb(a);return a}function tb(b,a){return(a=b.da.get(a.toLowerCase()))?a[0].R():b.ua()}
function kb(b,a){let c=b.ua();var d=b.da.get(a);if(d&&d.length){c=d[0].R();for(let f=0,g=d.length;f<g;++f){var e=d[f];f+1===g?e.U(b.ua()):e.U(d[f+1].R())}}for(const f of R(b,a))d=c,e=f.F||f.N,e.disconnect(),e.connect(d);b.Aa&&b.Kc===a&&(b.Aa.disconnect(),b.Aa.connect(c))}function*R(b,a){if(a)for(const c of b.L)b=c.aa,(b.length!==a.length?0:b===a||b.toLowerCase()===a.toLowerCase())&&(yield c);else b.ka&&!b.ka.S()&&(yield b.ka)}
function ub(b,a,c){return c?b.v.Be(a).then(d=>{const e=b.g.createBuffer(1,d.length,48E3);e.getChannelData(0).set(d);return e}):new Promise((d,e)=>{b.g.decodeAudioData(a,d,e)})}function vb(b,a){let c=0;for(let d=0,e=b.L.length;d<e;++d){const f=b.L[d];b.L[c]=f;f.M===a?f.j():++c}b.L.length=c}async function bb(b,a,c,d,e,f){for(const g of b.L)if(g.Wa()===c&&(g.ec()||f))return g.aa=e,g;a=await P(b,a,c,d,f);e="html5"===a.xc?new self.Vd(a.s,a,e):new self.Xd(a.s,a,e);b.L.push(e);return e}
function ab(b,a){let c=b.pb.get(a);if(!c){let d=null;c={Qc:0,promise:new Promise(e=>d=e),resolve:d};b.pb.set(a,c)}c.Qc++}function eb(b,a){a||(a=b.vd);return(b=b.pb.get(a))?b.promise:Promise.resolve()}function S(b){if(0<b.Ha.size)r(b);else for(const a of b.L)if(!a.G&&!a.S()){r(b);break}}function xb(b,a,c,d){k(b,"trigger",{type:a,tag:c,aiid:d})}function lb(b){b.Ic||(b.Ic=!0,Promise.resolve().then(()=>yb(b)))}
function yb(b){const a={};for(const [c,d]of b.da)a[c]=d.map(e=>e.Va());k(b,"fxstate",{fxstate:a});b.Ic=!1}
async function pb(b,a,c){if(3!==c){var d=a.bufferOriginalUrl,e=a.bufferUrl,f=a.bufferType,g=a.isMusic,h=a.tag,m=a.isLooping,p=a.volume,q=a.playbackTime;if(!g||1!==c)if(g||2!==c){c=null;try{c=await bb(b,d,e,f,h,g)}catch(t){console.error("[Construct] Audio: error loading audio state: ",t);return}b=c;a.pan?(Q(b,!0),d=b.F,e=d.pos,b.na[0]=e[0],b.na[1]=e[1],b.na[2]=e[2],e=d.orient,b.ma[0]=e[0],b.ma[1]=e[1],b.ma[2]=e[2],d.setPosition(...b.na),d.setOrientation(...b.ma),d.coneInnerAngle=d.cia,d.coneOuterAngle=
d.coa,d.coneOuterGain=d.cog,b.ja=d.uid):Q(b,!1);c.Play(m,p,q,0);a.isPlaying||c.Ya();c.tc(a)}}}function rb(b){console.error("[Audio] Offline rendering error: ",b)}
self.Ua=class extends self.wb{constructor(b){super(b,"audio");this.Ia=this.g=null;this.Ib=this.Fc=!1;this.ta=()=>{if(!this.Fc){var a=this.g;"suspended"===a.state&&a.resume&&a.resume();var c=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=c;d.connect(a.destination);d.start(0);"running"===a.state&&this.Ib&&(this.Fc=!0,window.removeEventListener("pointerup",this.ta,!0),window.removeEventListener("touchend",this.ta,!0),window.removeEventListener("click",this.ta,!0),window.removeEventListener("keydown",
this.ta,!0),this.Ib=!1)}};this.ca=[];this.L=[];this.ka=null;this.vd="";this.wd=-1;this.pb=new Map;this.Pb=1;this.ra=!1;this.Oc=0;this.ac=1;this.Dc=0;this.zd="HRTF";this.ld="inverse";this.Ad=600;this.yd=1E4;this.Cd=1;this.qd=this.Tb=!1;this.Fd=this.v.ae();this.da=new Map;this.Ha=new Set;this.rd=this.Ic=!1;this.Kc="";this.Aa=null;self.C3Audio_OnMicrophoneStream=(a,c)=>{this.Aa&&this.Aa.disconnect();this.Kc=c.toLowerCase();this.Aa=this.g.createMediaStreamSource(a);this.Aa.connect(tb(this,this.Kc))};
this.Gb=null;self.C3Audio_GetOutputStream=()=>{this.Gb||(this.Gb=this.g.createMediaStreamDestination(),this.Ia.connect(this.Gb));return this.Gb.stream};self.C3Audio_DOMInterface=this;aa(this,[["create-audio-context",a=>Ya(this,a)],["play",a=>$a(this,a)],["stop",a=>{a=a.tag;for(const c of R(this,a))c.pa()}],["stop-all",()=>{for(const a of this.L)a.pa()}],["set-paused",a=>{const c=a.tag;a=a.paused;for(const d of R(this,c))a?d.Ya():d.zb();S(this)}],["set-volume",a=>{const c=a.tag;a=a.vol;for(const d of R(this,
c))T(d,a)}],["fade-volume",a=>db(this,a)],["set-master-volume",a=>{this.Pb=a.vol;this.Ia.gain.value=this.Pb}],["set-muted",a=>{const c=a.tag;a=a.isMuted;for(const d of R(this,c))zb(d,a)}],["set-silent",a=>{this.ra=a.isSilent;this.v.Bb(this.ra);for(const c of this.L)c.Eb()}],["set-looping",a=>{const c=a.tag;a=a.isLooping;for(const d of R(this,c))d.nc(a)}],["set-playback-rate",a=>fb(this,a)],["seek",a=>gb(this,a)],["preload",a=>hb(this,a)],["unload",a=>ib(this,a)],["unload-all",()=>{for(const a of this.ca)a.j();
this.ca.length=0}],["set-suspended",a=>{a=a.isSuspended;!a&&this.g.resume&&this.g.resume();for(const c of this.L)c.oc(a);a&&this.g.suspend&&this.g.suspend()}],["add-effect",a=>jb(this,a)],["set-effect-param",a=>{const c=a.index,d=a.param,e=a.value,f=a.ramp,g=a.time;a=this.da.get(a.tag);!a||0>c||c>=a.length||(a[c].Z(d,e,f,g),lb(this))}],["remove-effects",a=>{a=a.tag.toLowerCase();const c=this.da.get(a);if(c&&c.length){for(const d of c)d.j();this.da.delete(a);kb(this,a)}}],["tick",a=>{this.ac=a.timeScale;
this.Dc=a.gameTime;this.wd=a.tickCount;if(0!==this.Oc)for(var c of this.L)c.xa();(c=a.listenerPos)&&this.g.listener.setPosition(c[0],c[1],c[2]);for(const d of a.instPans){a=d.uid;for(const e of this.L)e.ja===a&&cb(e,d.x,d.y,d.angle)}}],["load-state",a=>mb(this,a)],["offline-render-audio",a=>qb(this,a)],["offline-render-finish",()=>{this.g.resume()}]])}X(){return this.g}ua(){return this.Ia}xb(){return this.ra}wa(b){this.v.wa(b)}Ea(b){this.v.Ea(b)}Fa(){for(var b of this.Ha)b.Fa();b=this.g.currentTime;
for(var a of this.L)a.Fa(b);a=this.L.filter(c=>!c.G&&!c.S()).map(c=>c.Va());k(this,"state",{tickCount:this.wd,audioInstances:a,analysers:[...this.Ha].map(c=>({tag:c.aa,index:c.sd,peak:c.Na,rms:c.Bd,binCount:c.m.frequencyBinCount,freqBins:c.pd}))});0===a.length&&0===this.Ha.size&&this.Jb&&(this.v.ze(this.Gd),this.Jb=!1)}static ge(b){return b*Xa}static Wc(b){return Math.max(Math.min(Math.pow(10,b/20),1),0)}static de(b){return Math.log(Math.max(Math.min(b,1),0))/Math.log(10)*20}};self.Ab.dc(self.Ua);
"use strict";function sb(b){b.Nb||(b.Nb=b.sc());return b.Nb}self.Tc=class{constructor(b,a,c,d,e){this.s=b;this.He=a;this.Ba=c;this.T=d;this.Ee=e;this.xc="";this.Nb=null}j(){this.Nb=this.s=null}sc(){}X(){return this.s.X()}ic(){return this.He}Wa(){return this.Ba}hc(){return this.T}va(){return this.Ee}ha(){}};"use strict";
self.Ud=class extends self.Tc{constructor(b,a,c,d,e){super(b,a,c,d,e);this.xc="html5";this.K=new Audio;this.K.crossOrigin="anonymous";this.K.autoplay=!1;this.K.preload="auto";this.jb=this.kb=null;this.K.addEventListener("canplaythrough",()=>!0);this.ob=this.X().createGain();this.mb=null;this.K.addEventListener("canplay",()=>{this.kb&&(this.kb(),this.jb=this.kb=null);!this.mb&&this.K&&(this.mb=this.X().createMediaElementSource(this.K),this.mb.connect(this.ob))});this.onended=null;this.K.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.K.addEventListener("error",f=>{console.error(`[Construct] Audio '${this.Ba}' error: `,f);this.jb&&(this.jb(f),this.jb=this.kb=null)})}j(){vb(this.s,this);this.ob.disconnect();this.ob=null;this.mb.disconnect();this.mb=null;this.K&&!this.K.paused&&this.K.pause();this.K=this.onended=null;super.j()}sc(){return new Promise((b,a)=>{this.kb=b;this.jb=a;this.K.src=this.Ba})}P(){return this.K}ha(){return this.K.duration}};"use strict";
async function Bb(b){if(b.ya)return b.ya;var a=b.s.v;if("cordova"===a.D&&a.Yc(b.Ba)&&a.Kb)b.ya=await a.vb(b.Ba);else{a=await fetch(b.Ba);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);b.ya=await a.arrayBuffer()}}async function Cb(b){if(b.ba)return b.ba;b.ba=await ub(b.s,b.ya,b.Ge);b.ya=null}
self.Wd=class extends self.Tc{constructor(b,a,c,d,e,f){super(b,a,c,d,e);this.xc="webaudio";this.ba=this.ya=null;this.Ge=!!f}j(){vb(this.s,this);this.ba=this.ya=null;super.j()}async sc(){try{await Bb(this),await Cb(this)}catch(b){console.error(`[Construct] Failed to load audio '${this.Ba}': `,b)}}ha(){return this.ba?this.ba.duration:0}};"use strict";let Db=0;
function Q(b,a){a=!!a;b.hb!==a&&(b.hb=a,b.hb?(b.F||(b.F=b.X().createPanner(),b.F.panningModel=b.s.zd,b.F.distanceModel=b.s.ld,b.F.refDistance=b.s.Ad,b.F.maxDistance=b.s.yd,b.F.rolloffFactor=b.s.Cd),b.N.disconnect(),b.N.connect(b.F),b.F.connect(b.ua())):(b.F.disconnect(),b.N.disconnect(),b.N.connect(b.ua())))}function T(b,a){b.Ca=a;b.N.gain.cancelScheduledValues(0);b.eb=-1;b.N.gain.value=b.jc()}function zb(b,a){a=!!a;b.Ja!==a&&(b.Ja=a,b.Eb())}
function cb(b,a,c,d){b.hb&&(b.na[0]=a,b.na[1]=c,b.na[2]=0,b.ma[0]=Math.cos(d),b.ma[1]=Math.sin(d),b.ma[2]=0,b.F.setPosition(...b.na),b.F.setOrientation(...b.ma))}function U(b){return b.Jc?b.s.Dc:performance.now()/1E3}
self.Uc=class{constructor(b,a,c){this.s=b;this.M=a;this.aa=c;this.Fb=Db++;this.N=this.X().createGain();this.N.connect(this.ua());this.F=null;this.hb=!1;this.na=[0,0,0];this.ma=[0,0,0];this.G=!0;this.W=this.oa=this.I=!1;this.Ca=1;this.Ja=!1;this.fa=1;b=this.s.Oc;this.Jc=1===b&&!this.va()||2===b;this.eb=this.ja=-1;this.Ed=!1}j(){this.M=this.s=null;this.F&&(this.F.disconnect(),this.F=null);this.N.disconnect();this.N=null}X(){return this.s.X()}ua(){return tb(this.s,this.aa)}ic(){return this.M.ic()}Wa(){return this.M.Wa()}hc(){return this.M.hc()}va(){return this.M.va()}S(){}ec(){}IsPlaying(){return!this.G&&
!this.I&&!this.S()}Da(){}ha(){return this.M.ha()}Play(){}pa(){}Ya(){}zb(){}Fa(b){-1!==this.eb&&b>=this.eb&&(this.eb=-1,this.Ed&&this.pa(),xb(this.s,"fade-ended",this.aa,this.Fb))}jc(){const b=this.Ca;return isFinite(b)?b:0}xb(){return this.s.xb()}Eb(){}nc(){}xa(){}mc(){}oc(){}kc(){}Va(){var b=this.Fb,a=this.aa,c=this.ha(),d=this.Ca,e=this.IsPlaying();if(this.F){var f=this.F;f={pos:this.na,orient:this.ma,cia:f.coneInnerAngle,coa:f.coneOuterAngle,cog:f.coneOuterGain,uid:this.ja}}else f=null;return{aiid:b,
tag:a,duration:c,volume:d,isPlaying:e,playbackTime:this.Da(),playbackRate:this.fa,uid:this.ja,bufferOriginalUrl:this.ic(),bufferUrl:"",bufferType:this.hc(),isMusic:this.va(),isLooping:this.W,isMuted:this.Ja,resumePosition:this.kc(),pan:f}}tc(b){var a=b.playbackRate;this.fa!==a&&(this.fa=a,this.xa());zb(this,b.isMuted)}};"use strict";
self.Vd=class extends self.Uc{constructor(b,a,c){super(b,a,c);this.M.ob.connect(this.N);this.M.onended=()=>this.uc()}j(){this.pa();this.M.ob.disconnect();super.j()}P(){return this.M.P()}uc(){this.G=!0;this.ja=-1;xb(this.s,"ended",this.aa,this.Fb)}S(){return this.P().ended}ec(){return this.G?!0:this.S()}Da(){let b=this.P().currentTime;this.W||(b=Math.min(b,this.ha()));return b}Play(b,a,c){const d=this.P();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==b&&(d.loop=b);T(this,a);d.muted&&(d.muted=!1);
if(d.currentTime!==c)try{d.currentTime=c}catch(e){console.warn(`[Construct] Exception seeking audio '${this.M.Wa()}' to position '${c}': `,e)}this.s.wa(d);this.I=this.G=!1;this.W=b;this.fa=1}pa(){const b=this.P();b.paused||b.pause();this.s.Ea(b);this.G=!0;this.I=!1;this.ja=-1}Ya(){if(!(this.I||this.G||this.S())){var b=this.P();b.paused||b.pause();this.s.Ea(b);this.I=!0}}zb(){!this.I||this.G||this.S()||(this.s.wa(this.P()),this.I=!1)}Eb(){this.P().muted=this.Ja||this.xb()}nc(b){b=!!b;this.W!==b&&(this.W=
b,this.P().loop=b)}xa(){let b=this.fa;this.Jc&&(b*=this.s.ac);try{this.P().playbackRate=b}catch(a){console.warn(`[Construct] Unable to set playback rate '${b}':`,a)}}mc(b){if(!this.G&&!this.S())try{this.P().currentTime=b}catch(a){console.warn(`[Construct] Error seeking audio to '${b}': `,a)}}kc(){return this.Da()}oc(b){b?this.IsPlaying()?(this.P().pause(),this.oa=!0):this.oa=!1:this.oa&&(this.s.wa(this.P()),this.oa=!1)}};"use strict";function W(b){b.o&&b.o.disconnect();b.o=null;b.Za=null}
self.Xd=class extends self.Uc{constructor(b,a,c){super(b,a,c);this.o=null;this.Rb=d=>this.uc(d);this.Ec=!0;this.Za=null;this.O=this.Sb=this.Ub=0;this.Lc=1}j(){this.pa();W(this);this.Rb=null;super.j()}uc(b){this.I||this.oa||b.target!==this.Za||(this.G=this.Ec=!0,this.ja=-1,W(this),xb(this.s,"ended",this.aa,this.Fb))}S(){return!this.G&&this.o&&this.o.loop||this.I?!1:this.Ec}ec(){return!this.o||this.G?!0:this.S()}Da(){let b;b=this.I?this.O:this.Sb+(U(this)-this.Ub)*this.fa;this.W||(b=Math.min(b,this.ha()));
return b}Play(b,a,c,d){this.Lc=1;T(this,a);W(this);this.o=this.X().createBufferSource();this.o.buffer=this.M.ba;this.o.connect(this.N);this.Za=this.o;this.o.onended=this.Rb;this.o.loop=b;this.o.start(d,c);this.I=this.G=this.Ec=!1;this.W=b;this.fa=1;this.Ub=U(this);this.Sb=c}pa(){if(this.o)try{this.o.stop(0)}catch(b){}this.G=!0;this.I=!1;this.ja=-1}Ya(){this.I||this.G||this.S()||(this.O=this.Da(),this.W&&(this.O%=this.ha()),this.I=!0,this.o.stop(0))}zb(){!this.I||this.G||this.S()||(W(this),this.o=
this.X().createBufferSource(),this.o.buffer=this.M.ba,this.o.connect(this.N),this.Za=this.o,this.o.onended=this.Rb,this.o.loop=this.W,T(this,this.Ca),this.xa(),this.o.start(0,this.O),this.Ub=U(this),this.Sb=this.O,this.I=!1)}jc(){return super.jc()*this.Lc}Eb(){this.Lc=this.Ja||this.xb()?0:1;T(this,this.Ca)}nc(b){b=!!b;this.W!==b&&(this.W=b,this.o&&(this.o.loop=b))}xa(){let b=this.fa;this.Jc&&(b*=this.s.ac);this.o&&(this.o.playbackRate.value=b)}mc(b){this.G||this.S()||(this.I?this.O=b:(this.Ya(),this.O=
b,this.zb()))}kc(){return this.O}oc(b){b?this.IsPlaying()?(this.oa=!0,this.O=this.Da(),this.W&&(this.O%=this.ha()),this.o.stop(0)):this.oa=!1:this.oa&&(W(this),this.o=this.X().createBufferSource(),this.o.buffer=this.M.ba,this.o.connect(this.N),this.Za=this.o,this.o.onended=this.Rb,this.o.loop=this.W,T(this,this.Ca),this.xa(),this.o.start(0,this.O),this.Ub=U(this),this.Sb=this.O,this.oa=!1)}tc(b){super.tc(b);this.O=b.resumePosition}};"use strict";function X(b){return b.g.createGain()}
function Y(b,a,c,d,e){a.cancelScheduledValues(0);if(0===e)a.value=c;else switch(b=b.g.currentTime,e+=b,d){case 0:a.setValueAtTime(c,e);break;case 1:a.setValueAtTime(a.value,b);a.linearRampToValueAtTime(c,e);break;case 2:a.setValueAtTime(a.value,b),a.exponentialRampToValueAtTime(c,e)}}class Z{constructor(b){this.s=b;this.g=b.X();this.sd=-1;this.T=this.aa="";this.l=null}j(){this.g=null}R(){}U(){}Va(){return{type:this.T,tag:this.aa,params:this.l}}}
self.Od=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="filter";this.l=[a,c,d,e,f,g];this.u=X(this);this.i=X(this);this.i.gain.value=g;this.h=X(this);this.h.gain.value=1-g;this.B=this.g.createBiquadFilter();this.B.type=a;this.B.frequency.value=c;this.B.detune.value=d;this.B.Q.value=e;this.B.gain.vlaue=f;this.u.connect(this.B);this.u.connect(this.h);this.B.connect(this.i)}j(){this.u.disconnect();this.B.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[5]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 1:this.l[1]=a;Y(this,this.B.frequency,a,c,d);break;case 2:this.l[2]=a;Y(this,this.B.detune,a,c,d);break;case 3:this.l[3]=a;Y(this,this.B.Q,a,c,d);break;case 4:this.l[4]=a,Y(this,this.B.gain,a,c,d)}}};
self.Md=class extends Z{constructor(b,a,c,d){super(b);this.T="delay";this.l=[a,c,d];this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.lb=X(this);this.V=this.g.createDelay(a);this.V.delayTime.value=a;this.cb=X(this);this.cb.gain.value=c;this.u.connect(this.lb);this.u.connect(this.h);this.lb.connect(this.i);this.lb.connect(this.V);this.V.connect(this.cb);this.cb.connect(this.lb)}j(){this.u.disconnect();this.i.disconnect();this.h.disconnect();this.lb.disconnect();
this.V.disconnect();this.cb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}Z(b,a,c,d){const e=self.Ua.Wc;switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[2]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 4:this.l[1]=e(a);Y(this,this.cb.gain,e(a),c,d);break;case 5:this.l[0]=a,Y(this,this.V.delayTime,a,c,d)}}};
self.Ld=class extends Z{constructor(b,a,c,d){super(b);this.T="convolution";this.l=[c,d];this.jd=this.hd="";this.u=X(this);this.i=X(this);this.i.gain.value=d;this.h=X(this);this.h.gain.value=1-d;this.bb=this.g.createConvolver();this.bb.normalize=c;this.bb.buffer=a;this.u.connect(this.bb);this.u.connect(this.h);this.bb.connect(this.i)}j(){this.u.disconnect();this.bb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}Z(b,
a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.l[1]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,1-a,c,d)}}Va(){const b=super.Va();b.bufferOriginalUrl=this.hd;b.bufferUrl="";b.bufferType=this.jd;return b}};
self.Pd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="flanger";this.l=[a,c,d,e,f];this.u=X(this);this.h=X(this);this.h.gain.value=1-f/2;this.i=X(this);this.i.gain.value=f/2;this.fb=X(this);this.fb.gain.value=e;this.V=this.g.createDelay(a+c);this.V.delayTime.value=a;this.A=this.g.createOscillator();this.A.frequency.value=d;this.J=X(this);this.J.gain.value=c;this.u.connect(this.V);this.u.connect(this.h);this.V.connect(this.i);this.V.connect(this.fb);this.fb.connect(this.V);this.A.connect(this.J);
this.J.connect(this.V.delayTime);this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.V.disconnect();this.A.disconnect();this.J.disconnect();this.h.disconnect();this.i.disconnect();this.fb.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[4]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 6:this.l[1]=a/1E3;Y(this,this.J.gain,a/1E3,
c,d);break;case 7:this.l[2]=a;Y(this,this.A.frequency,a,c,d);break;case 8:this.l[3]=a/100,Y(this,this.fb.gain,a/100,c,d)}}};
self.Rd=class extends Z{constructor(b,a,c,d,e,f,g){super(b);this.T="phaser";this.l=[a,c,d,e,f,g];this.u=X(this);this.h=X(this);this.h.gain.value=1-g/2;this.i=X(this);this.i.gain.value=g/2;this.B=this.g.createBiquadFilter();this.B.type="allpass";this.B.frequency.value=a;this.B.detune.value=c;this.B.Q.value=d;this.A=this.g.createOscillator();this.A.frequency.value=f;this.J=X(this);this.J.gain.value=e;this.u.connect(this.B);this.u.connect(this.h);this.B.connect(this.i);this.A.connect(this.J);this.J.connect(this.B.frequency);
this.A.start(0)}j(){this.A.stop(0);this.u.disconnect();this.B.disconnect();this.A.disconnect();this.J.disconnect();this.h.disconnect();this.i.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[5]=a;Y(this,this.i.gain,a/2,c,d);Y(this,this.h.gain,1-a/2,c,d);break;case 1:this.l[0]=a;Y(this,this.B.frequency,a,c,d);break;case 2:this.l[1]=a;Y(this,this.B.detune,a,c,d);
break;case 3:this.l[2]=a;Y(this,this.B.Q,a,c,d);break;case 6:this.l[3]=a;Y(this,this.J.gain,a,c,d);break;case 7:this.l[4]=a,Y(this,this.A.frequency,a,c,d)}}};self.Qd=class extends Z{constructor(b,a){super(b);this.T="gain";this.l=[a];this.m=X(this);this.m.gain.value=a}j(){this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}Z(b,a,c,d){const e=self.Ua.Wc;switch(b){case 4:this.l[0]=e(a),Y(this,this.m.gain,e(a),c,d)}}};
self.Td=class extends Z{constructor(b,a,c){super(b);this.T="tremolo";this.l=[a,c];this.m=X(this);this.m.gain.value=1-c/2;this.A=this.g.createOscillator();this.A.frequency.value=a;this.J=X(this);this.J.gain.value=c/2;this.A.connect(this.J);this.J.connect(this.m.gain);this.A.start(0)}j(){this.A.stop(0);this.A.disconnect();this.J.disconnect();this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[1]=
a;Y(this,this.m.gain,1-a/2,c,d);Y(this,this.J.gain,a/2,c,d);break;case 7:this.l[0]=a,Y(this,this.A.frequency,a,c,d)}}};
self.Sd=class extends Z{constructor(b,a,c){super(b);this.T="ringmod";this.l=[a,c];this.u=X(this);this.i=X(this);this.i.gain.value=c;this.h=X(this);this.h.gain.value=1-c;this.rb=X(this);this.rb.gain.value=0;this.A=this.g.createOscillator();this.A.frequency.value=a;this.A.connect(this.rb.gain);this.A.start(0);this.u.connect(this.rb);this.u.connect(this.h);this.rb.connect(this.i)}j(){this.A.stop(0);this.A.disconnect();this.rb.disconnect();this.u.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();
this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0);this.l[1]=a;Y(this,this.i.gain,a,c,d);Y(this,this.h.gain,1-a,c,d);break;case 7:this.l[0]=a,Y(this,this.A.frequency,a,c,d)}}};
self.Nd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="distortion";this.l=[a,c,d,e,f];this.u=X(this);this.Yb=X(this);this.Xb=X(this);b=d;.01>b&&(b=.01);this.Yb.gain.value=b;this.Xb.gain.value=Math.pow(1/b,.6)*e;this.i=X(this);this.i.gain.value=f;this.h=X(this);this.h.gain.value=1-f;this.bc=this.g.createWaveShaper();this.Ac=new Float32Array(65536);for(e=0;32768>e;++e)f=e/32768,b=1.05*c*a-a,d=0>f?-f:f,d<a?b=d:(d=1-Math.exp(-(1/b)*(d-a)),b=a+b*d),f=b*(0>f?-1:1),this.Ac[32768+e]=f,this.Ac[32768-
e-1]=-f;this.bc.curve=this.Ac;this.u.connect(this.Yb);this.u.connect(this.h);this.Yb.connect(this.bc);this.bc.connect(this.Xb);this.Xb.connect(this.i)}j(){this.u.disconnect();this.Yb.disconnect();this.bc.disconnect();this.Xb.disconnect();this.i.disconnect();this.h.disconnect();super.j()}U(b){this.i.disconnect();this.i.connect(b);this.h.disconnect();this.h.connect(b)}R(){return this.u}Z(b,a,c,d){switch(b){case 0:a=Math.max(Math.min(a/100,1),0),this.l[4]=a,Y(this,this.i.gain,a,c,d),Y(this,this.h.gain,
1-a,c,d)}}};self.Kd=class extends Z{constructor(b,a,c,d,e,f){super(b);this.T="compressor";this.l=[a,c,d,e,f];this.m=this.g.createDynamicsCompressor();this.m.threshold.value=a;this.m.knee.value=c;this.m.ratio.value=d;this.m.attack.value=e;this.m.release.value=f}j(){this.m.disconnect();super.j()}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}Z(){}};
self.Jd=class extends Z{constructor(b,a,c){super(b);this.T="analyser";this.l=[a,c];this.m=this.g.createAnalyser();this.m.fftSize=a;this.m.smoothingTimeConstant=c;this.pd=new Float32Array(this.m.frequencyBinCount);this.Dd=new Uint8Array(a);this.Bd=this.Na=0;b=this.s;b.Ha.add(this);S(b)}j(){this.s.Ha.delete(this);this.m.disconnect();super.j()}Fa(){this.m.getFloatFrequencyData(this.pd);this.m.getByteTimeDomainData(this.Dd);const b=this.m.fftSize;let a=this.Na=0;for(var c=0;c<b;++c){let d=(this.Dd[c]-
128)/128;0>d&&(d=-d);this.Na<d&&(this.Na=d);a+=d*d}c=self.Ua.de;this.Na=c(this.Na);this.Bd=c(Math.sqrt(a/b))}U(b){this.m.disconnect();this.m.connect(b)}R(){return this.m}Z(){}};"use strict";async function Eb(b,a){a=a.type;let c=!0;0===a?c=await Fb():1===a&&(c=await Gb());k(b,"permission-result",{type:a,result:c})}
async function Fb(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request orientation permission: ",b),!1}}
async function Gb(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(b){return console.warn("[Touch] Failed to request motion permission: ",b),!1}}self.Ab.dc(class extends self.wb{constructor(b){super(b,"touch");n(this,"request-permission",a=>Eb(this,a))}});
